### ISSUE TITLE
Add link to documentation for deploying Flask in production

### ISSUE THREAD

**Issue by aVolpe** [open-contracting/kingfisher-process#298]
I have a kingfisher collect collecting the Paraguayan DNCP records using the [paraguay_dncp_records](https://github.com/open-contracting/kingfisher-collect/blob/master/kingfisher_scrapy/spiders/paraguay_dncp_records.py) spider.

After working for ~4 hours, kingfisher collect returns 500 and this exception is logged:

```
process_1  | 163.172.140.229 - - [30/May/2020 12:11:22] "POST /api/v1/submit/file/ HTTP/1.1" 500 -
process_1  | Traceback (most recent call last):
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
process_1  |     return self.wsgi_app(environ, start_response)
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
process_1  |     response = self.handle_exception(e)
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
process_1  |     reraise(exc_type, exc_value, tb)
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
process_1  |     raise value
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
process_1  |     response = self.full_dispatch_request()
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
process_1  |     rv = self.handle_user_exception(e)
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
process_1  |     reraise(exc_type, exc_value, tb)
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
process_1  |     raise value
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
process_1  |     rv = self.dispatch_request()
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
process_1  |     return self.view_functions[rule.endpoint](**req.view_args)
process_1  |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
process_1  |     return self.dispatch_request(*args, **kwargs)
process_1  |   File "/app/ocdskingfisherprocess/web/views_api_v1.py", line 91, in dispatch_request
process_1  |     self.collection_sample,
process_1  |   File "/app/ocdskingfisherprocess/store.py", line 37, in load_collection
process_1  |     collection_sample)
process_1  |   File "/app/ocdskingfisherprocess/database.py", line 354, in get_or_create_collection_id
process_1  |     transform_type=transform_type)
process_1  |   File "/app/ocdskingfisherprocess/database.py", line 334, in get_collection_id
process_1  |     with self.get_engine().begin() as connection:
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2061, in begin
process_1  |     conn = self.contextual_connect(close_with_result=close_with_result)
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2192, in contextual_connect
process_1  |     self._wrap_pool_connect(self.pool.connect, None),
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
process_1  |     return fn()
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool.py", line 434, in connect
process_1  |     return _ConnectionFairy._checkout(self)
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool.py", line 831, in _checkout
process_1  |     fairy = _ConnectionRecord.checkout(pool)
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool.py", line 563, in checkout
process_1  |     rec = pool._do_get()
process_1  |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool.py", line 1251, in _do_get
process_1  |     code="3o7r",
process_1  | sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

Following the information in the link, the cause can be:

* excesive load, unlikely because I have only one collect sending data
* pool isn't managed correctly
* long running transactions
* deadlock

I change the engine creation code to:

```python
            self._engine = sa.create_engine(
                self.config.database_uri,
                json_serializer=SetEncoder().encode,
                pool_size=10,
                max_overflow=200,
                json_deserializer=partial(
                    json.loads,
                    object_pairs_hook=collections.OrderedDict),
            )
```

To check if this fixes the issue, I will update this issue if this patch fix the issue.

#### Environment

* Dockerized environment
* redis 6.4
* scrapyd base image vimagick/scrapyd:py3
  * SCRAPY_VERSION=1.8.0
  * SCRAPYD_VERSION=1.2.1
* process
  * Kingfisher process e0da1d359bee18734f8bdfa1b81851a885fb52d7
  * python 3.7
  * environment=development
  * served with flask
* postgres
  * 12.2
  * Not in the same machine

**Comment by aVolpe** [comment]
The new pool size only delay the issue, aflter 8 hours the same issue.

**Comment by jpmckinney** [comment]
@aVolpe We run Kingfisher Process with much higher load, so I assume it has something to do with your deployment. How are you running the Flask app? We use uWSGI: https://github.com/open-contracting/deploy/blob/master/salt/uwsgi/ocdskingfisherprocess.ini

**Comment by jpmckinney** [comment]
It looks like Flask doesn't recommend using it's built-in server for production, so we should add options to our documentation on how to run the app with another server: https://flask.palletsprojects.com/en/1.1.x/deploying/

**Comment by aVolpe** [comment]
Hi @jpmckinney.

I was running using flask (I use [this documentation](https://kingfisher-process.readthedocs.io/en/latest/web.html)).

Maybe this is the fix: `harakiri = 900`

I will test and update the issue.
