### ISSUE TITLE
Running transform collections crash

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#72]
```
psycopg2.IntegrityError: duplicate key value violates unique constraint "unique_collection_file_item_identifiers"
DETAIL:  Key (collection_file_id, number)=(16, 0) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ocdskingfisher-process-cli", line 40, in <module>
    main()
  File "ocdskingfisher-process-cli", line 34, in main
    commands[args.subcommand].run_command(args)
  File "/vagrant-process/ocdskingfisherprocess/cli/commands/transform_collections.py", line 34, in run_command
    transform.process()
  File "/vagrant-process/ocdskingfisherprocess/transform/upgrade_1_0_to_1_1.py", line 12, in process
    self.process_file(file_model)
  File "/vagrant-process/ocdskingfisherprocess/transform/upgrade_1_0_to_1_1.py", line 19, in process_file
    self.process_file_item(file_model, file_item_model)
  File "/vagrant-process/ocdskingfisherprocess/transform/upgrade_1_0_to_1_1.py", line 33, in process_file_item
    self.process_release_row(file_model, file_item_model, release_row)
  File "/vagrant-process/ocdskingfisherprocess/transform/upgrade_1_0_to_1_1.py", line 58, in process_release_row
    self.store.store_file_item(file_model.filename, None, 'release_package', package, file_item_model.number)
  File "/vagrant-process/ocdskingfisherprocess/store.py", line 125, in store_file_item
    url=url) as store:
  File "/vagrant-process/ocdskingfisherprocess/database.py", line 489, in __enter__
    'store_start_at': datetime.datetime.utcnow(),
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
    distilled_params,
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
    e, statement, parameters, cursor, context
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/vagrant-process/.ve/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "unique_collection_file_item_identifiers"
DETAIL:  Key (collection_file_id, number)=(16, 0) already exists.
 [SQL: 'INSERT INTO collection_file_item (collection_file_id, store_start_at, number) VALUES (%(collection_file_id)s, %(store_start_at)s, %(number)s) RETURNING collection_file_item.id'] [parameters: {'collection_file_id': 16, 'store_start_at': datetime.datetime(2019, 2, 8, 12, 36, 3, 494986), 'number': 0}] (Background on this error at: http://sqlalche.me/e/gkpj)

```

**Comment by odscjames** [comment]
This could be just due to #25

**Comment by odscjames** [comment]
#25 is now fixed - so leaving this issue for a bit to see if it's fixed or if it comes back.

**Comment by jpmckinney** [comment]
No reported error occurrences in a month, so presuming fixed. Can always re-open if not the case.
